### ISSUE TITLE
Not able to run miniMAL as a library

### ISSUE THREAD

**Issue by whitelizard** [kanaka/miniMAL#34]
I only get:

`TypeError: Object prototype may only be an Object or null: undefined`

when running `node test.js`.
Where _test.js_ is:
```
const miniMAL = require('minimal-lisp');
const m = miniMAL();
m.eval(["+", 2, 3]);
```

**Comment by whitelizard** [comment]
As a minimal (pun inteded) setup for the error (in ubuntu 18.04):
```
mkdir minimal
cd minimal
npm init
npm i -S minimal-lisp
echo "const m = require('minimal-lisp')();" >> index.js
node index.js
```

**Comment by kanaka** [comment]
Hmm, interesting. I think this used to work in older versions of node. However, you can work around this by passing the top level environment you want to use. In node this is usually "global" although "{}" works too if you don't want access to node globals:

```js
const m = require('minimal-lisp')(global);
m.eval([".", "Math", ["`", "sqrt"], 5]);
```

I've updated the README to reflect the use of "global" as the top-level environment.

**Comment by whitelizard** [comment]
That's great, because I was wondering if there was a possibility of feeding a context somehow.

So, `global` and `{}` works, but the following does not:

```js
const m = require('minimal-lisp')({ foo: () => 5 });
console.log(m.eval(['.', 'foo']));
```

Isn't it supposed to work this way?

Also, this works:
```js
const m = require('minimal-lisp')(global);
console.log(m.eval(['.', 'Date', ['`', 'now']]));
```

but how do I get the equivalent of `new Date()`, for the possibility of using Date objects?

**Comment by kanaka** [comment]
The "." form is used to invoke a method on an object. Since "foo" is a regular function in the environment it can be invoked like this:

```js
const m1 = require('minimal-lisp')({ foo: () => 5 });
m1.eval(["foo"]);
```
Just for completeness, here is how you would invoke a method of the foo "object":

```js
m1.eval([".", "foo", ["`", "toString"]]);
```

Don't forget to quote the method name otherwise, the evaluator will attempt to resolve the string to something in the environment as use that resolution as the method name.

The "new" form is used for calling Object constructors:

```js
const m2 = require('minimal-lisp')(global);
m2.eval(["new", "Date"]);
```

As you've noticed the documentation for miniMAL is pretty minimal at the moment. Since you seemed to be working through how to use it it would be great if you could document what you learn along the way (to help those who come along after). I've created a nearly empty FAQ page (https://github.com/kanaka/miniMAL/wiki/FAQ) that you are free to add to. Anybody should be able to edit it. Unfortunately I don't have time to create comprehensive docs right now.

**Comment by whitelizard** [comment]
That was the final piece of the syntax puzzle in my head I think, thanks. It was so long since I coded any lisp-like language, and that was scheme :).

Just a small (probably last) question...

Is the following the simplest/best way to communicate back to JS?
```js
const mLisp = require('minimal-lisp');
const ctx = { vars: {} };
const m = mLisp(ctx);
m.eval(['.-', 'vars', ['`', 'test'], 8]);
console.log(ctx.vars.test);
```

PS. I'll add to the FAQ if I feel there's actually something missing in the docs

**Comment by kanaka** [comment]
That certainly works and depending on the broader context it might be a good approach. Another approach that comes to mind is passing in an update function from the JS side. This would give more freedom to change each side independently.

```js
const mLisp = require('minimal-lisp');
let vars = {};
function update_var(name, value) { vars[name] = value }
const m = mLisp({update_var: update_var});
m.eval(['update_var', ["`", "test"], 8])
console.log(vars.test)
```
