### ISSUE TITLE
Feature request: Ability to control side effects

### ISSUE THREAD

**Issue by whitelizard** [kanaka/miniMAL#35]
I would very much like to be able to control the environment that miniMAL instructions can execute in. The ability to set `miniMAL({})` does not prevent access to the whole of JS, including the dangerous global function `eval`.

Being able to have control, or prevent any crazy stuff potentially executing from a miniMAL program, would enable this library to be used for user customizable dynamic rules, like access rules, event rules etc, that can be stored as JSON in a database.

I guess that some second argument to miniMAL() preventing just the `"js"` feature, would do most of the trick? (But there would probably be a more general way to do it)

**Comment by kanaka** [comment]
The environment that is setup (for node) is shown here: https://github.com/kanaka/miniMAL/blob/gh-pages/js/stepB_node.js#L103

You can disable the "js" and/or "eval" symbol after the fact. Note that if you disable the "eval" symbol you will probably want to keep a copy first. I.e. the JS side can still invoke it but the miniMAL code will no longer have access.

```js
const mLisp = require('minimal-lisp');
m = mLisp({})
mEval = m.eval;
m.js = m.eval = function () { throw new Error("permission denied"); }
mEval(["eval", 123]);
```

It's not particularly clean but it should accomplish what you want. You can redefine/add/disable any of the default environment symbols using the same method.

**Comment by whitelizard** [comment]
That's great!
Just a small comment would be that I don't think `m.eval` is any problem, because then `m.rep`, `"try"`, `"if"` etc would be as big of a problem. But all these only call the parser `EVAL`, which would be safe, right?

Some tests:

```js
function evalTest(m, code) {
  try {
    console.log(m.eval(code));
  } catch (err) {
    console.log(err.message);
  }
}

const mLisp = require('minimal-lisp');
const m = mLisp({ Date });
m.js = function() {
  throw new Error('Permission denied');
};
evalTest(m, ['+', 1, 1]);
evalTest(m, ['new', 'Date']);
evalTest(m, ['eval', ['`', ['+', 2, 2]]]);
evalTest(m, ['eval', ['`', ['js', ['`', 'eval("2 + 3")']]]]); // try to backdoor native eval
evalTest(m, ['rep', ['`', '["+", 3, 3]']]);
evalTest(m, ['rep', ['`', '["js", ["`", "eval(\'3 + 4\')"]]']]); // try to backdoor native eval
evalTest(m, ['js', ['`', 'eval("4+5")']]);
evalTest(m, ['eval', ['`', '4 + 5']]);
```

Will output:

```
2
2018-05-05T11:49:51.870Z
4
Permission denied
6
Permission denied
Permission denied
undefined
```

All attempts to reach native eval fail = Success.

**Comment by kanaka** [comment]
Yes, if you're just trying to prevent the miniMAL code from having arbitrary access to the underlying JS environment then disabling "js" is probably enough.

An example of the the reason you might want to disable "eval" (and yes, you are correct that you would need to disable "rep" too) is so that you can do complete static analysis of the miniMAL code before running it. For example, if you are using miniMAL in an embedded context and you want to guarantee that the code will terminate in a finite amount of time (e.g. to prevent user scripts from hanging the context it is embedded in) you could analyze the code and guarantee that there are no recursive or mutually recursive calls. However, with "eval" you can hide function calls from the static analyzer and violate this guarantee. The "if" and "try" forms don't have this same problem.

**Comment by whitelizard** [comment]
I'm back! (after an unfortunate loss of some miniMAL related work I'd done, and after working in a whole other project)
I have updated the [FAQ](https://github.com/kanaka/miniMAL/wiki/FAQ), please check and correct it if necessary!

**Comment by kanaka** [comment]
@whitelizard look good. Feel free to continue to add updates as you discover new useful or surprising things but I'll close the ticket now.
